services:
  - type: web
    name: name-profile-api
    runtime: docker
    repo: https://github.com/Ali-Peter/NameClassifierApi.git   # change to your repo
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
  - type: pgsql
    name: name-profile-db
    plan: free