services:
  - type: web
    name: name-profile-api
    runtime: docker
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
  - type: pgsql
    name: name-profile-db
    plan: free